### ISSUE TITLE
[IDEA] Close Left Sidebar

### ISSUE THREAD

**Issue by kookma** [cdruan/tw5-captivate#3]
What do you think if Captivate have a shortcut to close the left sidebar?

**Comment by cdruan** [comment]
Looks like TW's default shortcut for toggling the sidebar works for the theme as well :) Try <kbd>Shift-Alt-S</kbd>. On my system, only the left <kbd>Alt</kbd> works...

**Comment by kookma** [comment]
> Try Shift-Alt-S.

Ah yes! works like a charm!
