### ISSUE TITLE
Better Icon Size 

### ISSUE THREAD

**Issue by kookma** [cdruan/tw5-captivate#8]
While captivate has tuned the icon size on toolbars and editor ribon, but there is an issue in icon size and padding of Create Wikilink dropdown. I have attached screenshot from both Gitbub/Demo page and my own installation.

**Expected behavior**
I may suggest, these icons/buttons follow the same size as other icons, or their size adjusted to match with Captivate theme.
Remove extra paddings (I will submit issue also on tiddlywiki.com)
Keep them in the same line as searchbox (when there is space)

![img_323_msedge](https://github.com/cdruan/tw5-captivate/assets/830394/70ae8b3a-8a2c-4651-96e3-94552e320f21)

**Comment by kookma** [comment]
see https://github.com/Jermolene/TiddlyWiki5/issues/7529

**Comment by cdruan** [comment]
Thank you @kookma. Although this issue is fixed in TiddlyWiki 5.3.0, I've made adjustments in the theme to support older versions of TiddlyWiki.
